//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWebOrtopediaVelásquez
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        public cita()
        {
            this.detalle_cita = new HashSet<detalle_cita>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int idPaciente { get; set; }
        public Nullable<int> idMedico { get; set; }
        public Nullable<int> idHorario { get; set; }
    
        public virtual Horarios Horarios { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual ICollection<detalle_cita> detalle_cita { get; set; }
    }
}
