//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWebOrtopediaVelásquez
{
    using System;
    using System.Collections.Generic;
    
    public partial class horarios
    {
        public horarios()
        {
            this.consulta = new HashSet<consulta>();
        }
    
        public int id { get; set; }
        public Nullable<System.TimeSpan> horai { get; set; }
        public Nullable<System.TimeSpan> horaf { get; set; }
    
        public virtual ICollection<consulta> consulta { get; set; }
    }
}
