//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWebOrtopediaVelásquez
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        public Horarios()
        {
            this.cita = new HashSet<cita>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Dia { get; set; }
        public Nullable<int> Ortopeda { get; set; }
        public string Hora { get; set; }
    
        public virtual ICollection<cita> cita { get; set; }
        public virtual Dias Dias { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
