//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWebOrtopediaVelásquez
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrtopediaVelásquezEntities : DbContext
    {
        public OrtopediaVelásquezEntities()
            : base("name=OrtopediaVelásquezEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cita> cita { get; set; }
        public DbSet<detalle_cita> detalle_cita { get; set; }
        public DbSet<Dias> Dias { get; set; }
        public DbSet<Horarios> Horarios { get; set; }
        public DbSet<ortesis> ortesis { get; set; }
        public DbSet<protesis> protesis { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tipoOrtesis> tipoOrtesis { get; set; }
        public DbSet<tipoProtesis> tipoProtesis { get; set; }
        public DbSet<TipoUsuario> TipoUsuario { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
