//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWebOrtopediaVelásquez
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente
    {
        public paciente()
        {
            this.consulta = new HashSet<consulta>();
        }
    
        public int id { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string email { get; set; }
        public string codigoPaciente { get; set; }
        public string contrasenya { get; set; }
        public Nullable<int> idSexo { get; set; }
        public int edad { get; set; }
        public string alergias { get; set; }
    
        public virtual ICollection<consulta> consulta { get; set; }
        public virtual sexo sexo { get; set; }
    }
}
