//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWebOrtopediaVelásquez
{
    using System;
    using System.Collections.Generic;
    
    public partial class sexo
    {
        public sexo()
        {
            this.administradores = new HashSet<administradores>();
            this.paciente = new HashSet<paciente>();
        }
    
        public int id { get; set; }
        public string sexo1 { get; set; }
    
        public virtual ICollection<administradores> administradores { get; set; }
        public virtual ICollection<paciente> paciente { get; set; }
    }
}
