//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWebOrtopediaVelásquez
{
    using System;
    using System.Collections.Generic;
    
    public partial class su
    {
        public su()
        {
            this.administradores = new HashSet<administradores>();
        }
    
        public string su1 { get; set; }
        public string clave { get; set; }
    
        public virtual ICollection<administradores> administradores { get; set; }
    }
}
