//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWebOrtopediaVelásquez
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoProtesis
    {
        public tipoProtesis()
        {
            this.protesis = new HashSet<protesis>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public byte[] foto { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<protesis> protesis { get; set; }
    }
}
